# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dimas-mufid-notes',
                'doc_host': 'https://dimasmufid.github.io',
                'git_url': 'https://github.com/dimasmufid/dimas-mufid-notes',
                'lib_path': 'dimas_mufid_notes'},
  'syms': {'dimas_mufid_notes.core': {'dimas_mufid_notes.core.foo': ('core.html#foo', 'dimas_mufid_notes/core.py')}}}
